services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./back:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
  # user: 1000:1000
    tty: true
    environment:
      POSTGRES_DB: lost_item
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      TZ: "Asia/Tokyo"
      GOOGLE_APPLICATION_CREDENTIALS: "/app/service-account.json"

  db:
    image: postgres:14
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: lost_item
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      TZ: "Asia/Tokyo"
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  postgres_volume: