version: "3.9"
services:
  api:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./back:/app
    ports:
      - "3030:3000"
    depends_on:
      - db
    tty: true
    environment:
      POSTGRES_DB: lost-item
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      TZ: "Asia/Tokyo"

  db:
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: lost-item
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      TZ: "Asia/Tokyo"
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  postgres_volume: